import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1776272606398 implements MigrationInterface {
    name = 'InitialSchema1776272606398'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "permissions" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "description" character varying, "section" character varying, CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "role_id" varchar(40) NOT NULL, "permission_id" varchar(40) NOT NULL, CONSTRAINT "PK_84059017c90bfcb701b8fa42297" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "roles" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "description" character varying, "is_system_role" boolean NOT NULL DEFAULT false, "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "first_name" character varying NOT NULL, "last_name" character varying NOT NULL, "email" character varying NOT NULL, "password_hash" character varying NOT NULL, "phone" character varying, "status" character varying NOT NULL DEFAULT 'active', "role_id" varchar(40) NOT NULL, "last_login_at" TIMESTAMP, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "warehouses" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "branch_id" character varying NOT NULL, "name" character varying NOT NULL, "type" character varying NOT NULL DEFAULT 'physical', "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_56ae21ee2432b2270b48867e4be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taxes" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "rate" numeric(5,2) NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_6c58c9cbb420c4f65e3f5eb8162" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "suppliers" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "tax_id" character varying, "primary_contact" character varying, "phone" character varying, "email" character varying, "payment_condition" character varying, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_b70ac51766a9e3144f778cfe81e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "units_of_measure" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "abbreviation" character varying NOT NULL, "type" character varying NOT NULL, CONSTRAINT "PK_ce93a9c86be10704b5415ca4bee" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_order_items" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "purchase_order_id" varchar(40) NOT NULL, "product_id" character varying NOT NULL, "quantity" numeric(12,2) NOT NULL, "unit_cost" numeric(12,2) NOT NULL, "subtotal" numeric(12,2) NOT NULL, CONSTRAINT "PK_e8b7568d25c41e3290db596b312" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_orders" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "supplier_id" character varying NOT NULL, "branch_id" character varying, "date" TIMESTAMP NOT NULL DEFAULT now(), "status" character varying NOT NULL DEFAULT 'draft', "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "taxes" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, CONSTRAINT "PK_05148947415204a897e8beb2553" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "purchase_receptions" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "purchase_order_id" character varying NOT NULL, "date" TIMESTAMP NOT NULL DEFAULT now(), "warehouse_id" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', "notes" text, CONSTRAINT "PK_879528e4c3ad22d88ca15b07b06" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "product_variants" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "product_id" varchar(40) NOT NULL, "code" character varying NOT NULL, "attributes" jsonb, "price" numeric(12,2), "cost" numeric(12,2), "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_281e3f2c55652d6a22c0aa59fd7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "products" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "sku" character varying, "name" character varying NOT NULL, "description" text, "category_id" character varying, "brand_id" character varying, "unit_id" character varying, "product_type" character varying NOT NULL DEFAULT 'physical', "base_price" numeric(12,2) NOT NULL DEFAULT '0', "base_cost" numeric(12,2) NOT NULL DEFAULT '0', "controls_stock" boolean NOT NULL DEFAULT true, "min_stock" integer NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'draft', CONSTRAINT "UQ_c44ac33a05b144dd0d9ddcf9327" UNIQUE ("sku"), CONSTRAINT "PK_0806c755e0aca124e67c0cf6d7d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "price_lists" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "currency" character varying NOT NULL DEFAULT 'ARS', "valid_from" date, "valid_until" date, "status" character varying NOT NULL DEFAULT 'active', "is_default" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_fd66ee20b065696da25c97fa45a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "price_list_items" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "price_list_id" varchar(40) NOT NULL, "product_id" character varying NOT NULL, "price" numeric(12,2) NOT NULL, "min_quantity" integer NOT NULL DEFAULT '1', CONSTRAINT "PK_cdb44449658589feac39de86695" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payment_conditions" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "days" integer NOT NULL DEFAULT '0', "description" character varying, CONSTRAINT "PK_da059455aa54bd427788982c06b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "type" character varying NOT NULL, "date" TIMESTAMP NOT NULL DEFAULT now(), "customer_id" character varying, "supplier_id" character varying, "payment_method" character varying NOT NULL, "amount" numeric(12,2) NOT NULL, "currency" character varying NOT NULL DEFAULT 'ARS', "external_reference" character varying, "status" character varying NOT NULL DEFAULT 'draft', "notes" text, CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoices" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "order_id" character varying, "type_id" character varying, "number" character varying, "issue_date" date, "customer_id" character varying NOT NULL, "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "taxes" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'draft', "fiscal_integration_status" character varying, "notes" text, CONSTRAINT "PK_668cef7c22a427fd822cc1be3ce" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "invoice_types" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "code" character varying NOT NULL, "description" character varying, CONSTRAINT "UQ_a2a298cbe91eb64723bc7b42d9e" UNIQUE ("code"), CONSTRAINT "PK_e4fe6245208186d2febbc1f2c24" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "contacts" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "customer_id" varchar(40) NOT NULL, "name" character varying NOT NULL, "position" character varying, "email" character varying, "phone" character varying, "is_primary" boolean NOT NULL DEFAULT false, CONSTRAINT "PK_b99cd40cfd66a99f1571f4f72e6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "customers" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "customer_type" character varying NOT NULL DEFAULT 'company', "legal_name" character varying NOT NULL, "commercial_name" character varying, "tax_id" character varying, "tax_condition" character varying, "channel" character varying, "assigned_seller_id" character varying, "price_list_id" character varying, "credit_limit" numeric(12,2) NOT NULL DEFAULT '0', "status" character varying NOT NULL DEFAULT 'draft', "phone" character varying, "email" character varying, CONSTRAINT "PK_133ec679a801fab5e070f73d3ea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "addresses" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "customer_id" varchar(40) NOT NULL, "type" character varying NOT NULL DEFAULT 'shipping', "street" character varying NOT NULL, "city" character varying, "province" character varying, "country" character varying, "postal_code" character varying, "notes" character varying, CONSTRAINT "PK_745d8f43d3af10ab8247465e450" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "integrations" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "provider" character varying NOT NULL, "type" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'inactive', "credentials_ref" character varying, "configuration" jsonb, "last_sync_at" TIMESTAMP, CONSTRAINT "PK_9adcdc6d6f3922535361ce641e8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "integration_events" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "integration_id" varchar(40) NOT NULL, "event_type" character varying NOT NULL, "external_reference" character varying, "internal_reference" character varying, "status" character varying NOT NULL DEFAULT 'pending', "detail" jsonb, CONSTRAINT "PK_a2d1c976c11f47866a9e4273192" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "product_id" character varying NOT NULL, "variant_id" character varying, "warehouse_id" character varying NOT NULL, "available_qty" numeric(12,2) NOT NULL DEFAULT '0', "reserved_qty" numeric(12,2) NOT NULL DEFAULT '0', "in_transit_qty" numeric(12,2) NOT NULL DEFAULT '0', "min_stock" numeric(12,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_4859167c3b03980488504c5d917" UNIQUE ("product_id", "variant_id", "warehouse_id"), CONSTRAINT "PK_092bc1fc7d860426a1dec5aa8e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "companies" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "razon_social" character varying NOT NULL, "nombre_comercial" character varying NOT NULL, "moneda_base" character varying NOT NULL DEFAULT 'ARS', "pais" character varying NOT NULL DEFAULT 'AR', "tax_ids" jsonb, "logo_url" character varying, "phone" character varying, "email" character varying, "address" text, "timezone" character varying NOT NULL DEFAULT 'America/Argentina/Buenos_Aires', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_d4bc3e82a314fa9e29f652c2c22" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "categories" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "parent_id" varchar(40), "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_24dbc6126a28ff948da33e97d3b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cashbox_sessions" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "cashbox_id" varchar(40) NOT NULL, "opened_by" character varying NOT NULL, "opened_at" TIMESTAMP NOT NULL, "closed_by" character varying, "closed_at" TIMESTAMP, "opening_balance" numeric(12,2) NOT NULL, "closing_balance" numeric(12,2), "expected_balance" numeric(12,2), "difference" numeric(12,2), "notes" text, CONSTRAINT "PK_b4b5883a9b16f548e34e208973b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "cashboxes" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "branch_id" character varying NOT NULL, "name" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'closed', CONSTRAINT "PK_a7a5168173c43cb11448fc30d42" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_movements" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "type" character varying NOT NULL, "date" TIMESTAMP NOT NULL DEFAULT NOW(), "product_id" character varying NOT NULL, "variant_id" character varying, "source_warehouse_id" character varying, "dest_warehouse_id" character varying, "quantity" numeric(12,2) NOT NULL, "reason" character varying, "reference_type" character varying, "reference_id" character varying, "user_id" character varying, CONSTRAINT "PK_57a26b190618550d8e65fb860e7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "stock_reservations" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "order_id" character varying NOT NULL, "product_id" character varying NOT NULL, "variant_id" character varying, "warehouse_id" character varying NOT NULL, "quantity" numeric(12,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_46ec0f5605d70f64654ad4e7bd9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "branches" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "company_id" varchar(40) NOT NULL, "name" character varying NOT NULL, "code" character varying NOT NULL, "address" text, "phone" character varying, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "UQ_9c06cbb83feb2f0be6263bd47ee" UNIQUE ("code"), CONSTRAINT "PK_7f37d3b42defea97f1df0d19535" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "orders" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "number" SERIAL NOT NULL, "customer_id" character varying NOT NULL, "branch_id" character varying, "seller_id" character varying, "channel" character varying, "status" character varying NOT NULL DEFAULT 'draft', "estimated_delivery_date" date, "subtotal" numeric(12,2) NOT NULL DEFAULT '0', "taxes" numeric(12,2) NOT NULL DEFAULT '0', "discounts" numeric(12,2) NOT NULL DEFAULT '0', "total" numeric(12,2) NOT NULL DEFAULT '0', "notes" text, CONSTRAINT "PK_710e2d4957aa5878dfe94e4ac2f" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "order_items" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "order_id" varchar(40) NOT NULL, "product_id" character varying NOT NULL, "variant_id" character varying, "quantity" numeric(12,2) NOT NULL, "unit_price" numeric(12,2) NOT NULL, "discount" numeric(12,2) NOT NULL DEFAULT '0', "tax" numeric(12,2) NOT NULL DEFAULT '0', "subtotal" numeric(12,2) NOT NULL, CONSTRAINT "PK_005269d8574e6fac0493715c308" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "brands" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "name" character varying NOT NULL, "status" character varying NOT NULL DEFAULT 'active', CONSTRAINT "PK_b0c437120b624da1034a81fc561" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "current_balance" numeric(12,2) NOT NULL DEFAULT '0', "overdue_balance" numeric(12,2) NOT NULL DEFAULT '0', "credit_limit" numeric(12,2) NOT NULL DEFAULT '0', CONSTRAINT "UQ_0b2c7dd4f5da9187705c30888ac" UNIQUE ("entity_type", "entity_id"), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "account_entries" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "deleted_at" TIMESTAMP, "metadata" jsonb, "account_id" varchar(40) NOT NULL, "date" TIMESTAMP NOT NULL DEFAULT now(), "type" character varying NOT NULL, "concept" character varying NOT NULL, "reference_type" character varying, "reference_id" character varying, "amount" numeric(12,2) NOT NULL, "resulting_balance" numeric(12,2) NOT NULL, "status" character varying NOT NULL DEFAULT 'pending', CONSTRAINT "PK_4378c8454b064f22303906c5da4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "audit_events" ("id" varchar(40) NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), "metadata" jsonb, "actor_type" character varying NOT NULL, "actor_id" character varying, "action" character varying NOT NULL, "entity_type" character varying NOT NULL, "entity_id" character varying NOT NULL, "previous_state" jsonb, "new_state" jsonb, "ip_address" character varying, "result" character varying NOT NULL DEFAULT 'success', CONSTRAINT "PK_910f64d901a5c3e9878f0d4a407" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" ADD CONSTRAINT "FK_3f92bb44026cedfe235c8b91244" FOREIGN KEY ("purchase_order_id") REFERENCES "purchase_orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "product_variants" ADD CONSTRAINT "FK_6343513e20e2deab45edfce1316" FOREIGN KEY ("product_id") REFERENCES "products"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_list_items" ADD CONSTRAINT "FK_2576ee6c421b653f85011b9f5ac" FOREIGN KEY ("price_list_id") REFERENCES "price_lists"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "contacts" ADD CONSTRAINT "FK_3857e3d5137fea5865651a1be75" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "addresses" ADD CONSTRAINT "FK_7482082bf53fd0ba88a32e3de88" FOREIGN KEY ("customer_id") REFERENCES "customers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "integration_events" ADD CONSTRAINT "FK_a1b2a8f233048a164702859c0eb" FOREIGN KEY ("integration_id") REFERENCES "integrations"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "categories" ADD CONSTRAINT "FK_88cea2dc9c31951d06437879b40" FOREIGN KEY ("parent_id") REFERENCES "categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "cashbox_sessions" ADD CONSTRAINT "FK_edb0b6d63c1ffeebb8ded737efc" FOREIGN KEY ("cashbox_id") REFERENCES "cashboxes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "branches" ADD CONSTRAINT "FK_5973f79e64a27c506b07cd84b29" FOREIGN KEY ("company_id") REFERENCES "companies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "order_items" ADD CONSTRAINT "FK_145532db85752b29c57d2b7b1f1" FOREIGN KEY ("order_id") REFERENCES "orders"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_entries" ADD CONSTRAINT "FK_c3be9b07820be8450161d6ba4d2" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "account_entries" DROP CONSTRAINT "FK_c3be9b07820be8450161d6ba4d2"`);
        await queryRunner.query(`ALTER TABLE "order_items" DROP CONSTRAINT "FK_145532db85752b29c57d2b7b1f1"`);
        await queryRunner.query(`ALTER TABLE "branches" DROP CONSTRAINT "FK_5973f79e64a27c506b07cd84b29"`);
        await queryRunner.query(`ALTER TABLE "cashbox_sessions" DROP CONSTRAINT "FK_edb0b6d63c1ffeebb8ded737efc"`);
        await queryRunner.query(`ALTER TABLE "categories" DROP CONSTRAINT "FK_88cea2dc9c31951d06437879b40"`);
        await queryRunner.query(`ALTER TABLE "integration_events" DROP CONSTRAINT "FK_a1b2a8f233048a164702859c0eb"`);
        await queryRunner.query(`ALTER TABLE "addresses" DROP CONSTRAINT "FK_7482082bf53fd0ba88a32e3de88"`);
        await queryRunner.query(`ALTER TABLE "contacts" DROP CONSTRAINT "FK_3857e3d5137fea5865651a1be75"`);
        await queryRunner.query(`ALTER TABLE "price_list_items" DROP CONSTRAINT "FK_2576ee6c421b653f85011b9f5ac"`);
        await queryRunner.query(`ALTER TABLE "product_variants" DROP CONSTRAINT "FK_6343513e20e2deab45edfce1316"`);
        await queryRunner.query(`ALTER TABLE "purchase_order_items" DROP CONSTRAINT "FK_3f92bb44026cedfe235c8b91244"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_a2cecd1a3531c0b041e29ba46e1"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`DROP TABLE "audit_events"`);
        await queryRunner.query(`DROP TABLE "account_entries"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "brands"`);
        await queryRunner.query(`DROP TABLE "order_items"`);
        await queryRunner.query(`DROP TABLE "orders"`);
        await queryRunner.query(`DROP TABLE "branches"`);
        await queryRunner.query(`DROP TABLE "stock_reservations"`);
        await queryRunner.query(`DROP TABLE "stock_movements"`);
        await queryRunner.query(`DROP TABLE "cashboxes"`);
        await queryRunner.query(`DROP TABLE "cashbox_sessions"`);
        await queryRunner.query(`DROP TABLE "categories"`);
        await queryRunner.query(`DROP TABLE "companies"`);
        await queryRunner.query(`DROP TABLE "stock"`);
        await queryRunner.query(`DROP TABLE "integration_events"`);
        await queryRunner.query(`DROP TABLE "integrations"`);
        await queryRunner.query(`DROP TABLE "addresses"`);
        await queryRunner.query(`DROP TABLE "customers"`);
        await queryRunner.query(`DROP TABLE "contacts"`);
        await queryRunner.query(`DROP TABLE "invoice_types"`);
        await queryRunner.query(`DROP TABLE "invoices"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TABLE "payment_conditions"`);
        await queryRunner.query(`DROP TABLE "price_list_items"`);
        await queryRunner.query(`DROP TABLE "price_lists"`);
        await queryRunner.query(`DROP TABLE "products"`);
        await queryRunner.query(`DROP TABLE "product_variants"`);
        await queryRunner.query(`DROP TABLE "purchase_receptions"`);
        await queryRunner.query(`DROP TABLE "purchase_orders"`);
        await queryRunner.query(`DROP TABLE "purchase_order_items"`);
        await queryRunner.query(`DROP TABLE "units_of_measure"`);
        await queryRunner.query(`DROP TABLE "suppliers"`);
        await queryRunner.query(`DROP TABLE "taxes"`);
        await queryRunner.query(`DROP TABLE "warehouses"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
    }

}
