export const PERMISSIONS = {
  USERS: {
    VIEW: 'users:view',
    CREATE: 'users:create',
    UPDATE: 'users:update',
    DELETE: 'users:delete',
    UPDATE_ROLE: 'users:update_role',
    UPDATE_PASSWORD: 'users:update_password',
  },
  ROLES: {
    VIEW: 'roles:view',
    CREATE: 'roles:create',
    UPDATE: 'roles:update',
    DELETE: 'roles:delete',
  },
  COMPANY: {
    VIEW: 'company:view',
    UPDATE: 'company:update',
  },
  BRANCHES: {
    VIEW: 'branches:view',
    CREATE: 'branches:create',
    UPDATE: 'branches:update',
    DELETE: 'branches:delete',
  },
  WAREHOUSES: {
    VIEW: 'warehouses:view',
    CREATE: 'warehouses:create',
    UPDATE: 'warehouses:update',
    DELETE: 'warehouses:delete',
  },
  CATEGORIES: {
    VIEW: 'categories:view',
    CREATE: 'categories:create',
    UPDATE: 'categories:update',
    DELETE: 'categories:delete',
  },
  BRANDS: {
    VIEW: 'brands:view',
    CREATE: 'brands:create',
    UPDATE: 'brands:update',
    DELETE: 'brands:delete',
  },
  TAXES: {
    VIEW: 'taxes:view',
    CREATE: 'taxes:create',
    UPDATE: 'taxes:update',
    DELETE: 'taxes:delete',
  },
  UNITS: {
    VIEW: 'units:view',
    CREATE: 'units:create',
    UPDATE: 'units:update',
    DELETE: 'units:delete',
  },
  PRICE_LISTS: {
    VIEW: 'price_lists:view',
    CREATE: 'price_lists:create',
    UPDATE: 'price_lists:update',
    DELETE: 'price_lists:delete',
  },
  CUSTOMERS: {
    VIEW: 'customers:view',
    CREATE: 'customers:create',
    UPDATE: 'customers:update',
    DELETE: 'customers:delete',
    BLOCK: 'customers:block',
    UNBLOCK: 'customers:unblock',
  },
  PRODUCTS: {
    VIEW: 'products:view',
    CREATE: 'products:create',
    UPDATE: 'products:update',
    DELETE: 'products:delete',
    UPDATE_PRICE: 'products:update_price',
    UPDATE_COST: 'products:update_cost',
    DISCONTINUE: 'products:discontinue',
  },
  INVENTORY: {
    VIEW: 'inventory:view',
    ADJUST: 'inventory:adjust',
    TRANSFER: 'inventory:transfer',
    RESERVE: 'inventory:reserve',
    RELEASE: 'inventory:release',
    EXPIRE: 'inventory:expire',
    COUNT: 'inventory:count',
  },
  ORDERS: {
    VIEW: 'orders:view',
    CREATE: 'orders:create',
    UPDATE: 'orders:update',
    CONFIRM: 'orders:confirm',
    REJECT: 'orders:reject',
    CANCEL: 'orders:cancel',
    DISPATCH: 'orders:dispatch',
    DELIVER: 'orders:deliver',
    COMPLETE: 'orders:complete',
    OVERRIDE_PRICE: 'orders:override_price',
  },
  INVOICE_TYPES: {
    VIEW: 'invoice_types:view',
    CREATE: 'invoice_types:create',
    UPDATE: 'invoice_types:update',
    DELETE: 'invoice_types:delete',
  },
  INVOICES: {
    VIEW: 'invoices:view',
    CREATE: 'invoices:create',
    ISSUE: 'invoices:issue',
    VOID: 'invoices:void',
    CANCEL: 'invoices:cancel',
    REQUEST_CAE: 'invoices:request_cae',
    CANCEL_CAE: 'invoices:cancel_cae',
  },
  ACCOUNTS: {
    VIEW: 'accounts:view',
    CREATE_ENTRY: 'accounts:create_entry',
    SETTLE: 'accounts:settle',
  },
  PAYMENT_CONDITIONS: {
    VIEW: 'payment_conditions:view',
    CREATE: 'payment_conditions:create',
    UPDATE: 'payment_conditions:update',
    DELETE: 'payment_conditions:delete',
  },
  PAYMENT_METHODS: {
    VIEW: 'payment_methods:view',
    CREATE: 'payment_methods:create',
    UPDATE: 'payment_methods:update',
    DELETE: 'payment_methods:delete',
  },
  PAYMENTS: {
    VIEW: 'payments:view',
    CREATE: 'payments:create',
    APPLY: 'payments:apply',
    RECONCILE: 'payments:reconcile',
    CANCEL: 'payments:cancel',
  },
  CASHBOX: {
    VIEW: 'cashbox:view',
    MANAGE: 'cashbox:manage',
    OPEN: 'cashbox:open',
    CLOSE: 'cashbox:close',
    CLOSE_WITH_DIFF: 'cashbox:close_with_diff',
  },
  SUPPLIERS: {
    VIEW: 'suppliers:view',
    CREATE: 'suppliers:create',
    UPDATE: 'suppliers:update',
    DELETE: 'suppliers:delete',
  },
  PURCHASES: {
    VIEW: 'purchases:view',
    CREATE: 'purchases:create',
    UPDATE: 'purchases:update',
    APPROVE: 'purchases:approve',
    SEND: 'purchases:send',
    RECEIVE: 'purchases:receive',
    CANCEL: 'purchases:cancel',
  },
  REPORTS: {
    VIEW: 'reports:view',
    EXPORT: 'reports:export',
    VIEW_FINANCIAL: 'reports:view_financial',
    VIEW_LOGISTICS: 'reports:view_logistics',
  },
  AUDIT: {
    VIEW: 'audit:view',
  },
  INTEGRATIONS: {
    VIEW: 'integrations:view',
    CREATE: 'integrations:create',
    UPDATE: 'integrations:update',
    PAUSE: 'integrations:pause',
    DELETE: 'integrations:delete',
  },
  SETTINGS: {
    VIEW: 'settings:view',
    UPDATE: 'settings:update',
  },
  SALES_ZONES: {
    VIEW: 'sales_zones:view',
    CREATE: 'sales_zones:create',
    UPDATE: 'sales_zones:update',
    DELETE: 'sales_zones:delete',
  },
  ROUTES: {
    VIEW: 'routes:view',
    CREATE: 'routes:create',
    UPDATE: 'routes:update',
    DELETE: 'routes:delete',
    ASSIGN: 'routes:assign',
  },
  PROMOTIONS: {
    VIEW: 'promotions:view',
    CREATE: 'promotions:create',
    UPDATE: 'promotions:update',
    DELETE: 'promotions:delete',
    ACTIVATE: 'promotions:activate',
  },
  COMMISSIONS: {
    VIEW: 'commissions:view',
    APPROVE: 'commissions:approve',
    REVERSE: 'commissions:reverse',
    SETTLE: 'commissions:settle',
  },
  CUSTOMER_VISITS: {
    VIEW: 'customer_visits:view',
    CREATE: 'customer_visits:create',
  },
  WAREHOUSE_LOCATIONS: {
    VIEW: 'warehouse_locations:view',
    CREATE: 'warehouse_locations:create',
    UPDATE: 'warehouse_locations:update',
    DELETE: 'warehouse_locations:delete',
  },
  LOTS: {
    VIEW: 'lots:view',
    CREATE: 'lots:create',
    UPDATE: 'lots:update',
    BLOCK: 'lots:block',
    UNBLOCK: 'lots:unblock',
  },
  PICKING: {
    VIEW: 'picking:view',
    CREATE: 'picking:create',
    ASSIGN: 'picking:assign',
    START: 'picking:start',
    PICK: 'picking:pick',
    COMPLETE: 'picking:complete',
    CANCEL: 'picking:cancel',
  },
  SHIPMENTS: {
    VIEW: 'shipments:view',
    CREATE: 'shipments:create',
    UPDATE: 'shipments:update',
    LOAD: 'shipments:load',
    DEPART: 'shipments:depart',
    COMPLETE: 'shipments:complete',
    CANCEL: 'shipments:cancel',
    DELIVER_STOP: 'shipments:deliver_stop',
    REJECT_STOP: 'shipments:reject_stop',
  },
  VEHICLES: {
    VIEW: 'vehicles:view',
    CREATE: 'vehicles:create',
    UPDATE: 'vehicles:update',
    DELETE: 'vehicles:delete',
  },
  DRIVERS: {
    VIEW: 'drivers:view',
    CREATE: 'drivers:create',
    UPDATE: 'drivers:update',
    DELETE: 'drivers:delete',
  },
  DISPATCH_SHEETS: {
    VIEW: 'dispatch_sheets:view',
    CREATE: 'dispatch_sheets:create',
    UPDATE: 'dispatch_sheets:update',
    PRINT: 'dispatch_sheets:print',
    CLOSE: 'dispatch_sheets:close',
  },
  RETURNS: {
    VIEW: 'returns:view',
    CREATE: 'returns:create',
    CONFIRM: 'returns:confirm',
    RECEIVE: 'returns:receive',
    INSPECT: 'returns:inspect',
    CLOSE: 'returns:close',
    CANCEL: 'returns:cancel',
  },
  INVENTORY_COUNTS: {
    VIEW: 'inventory_counts:view',
    CREATE: 'inventory_counts:create',
    START: 'inventory_counts:start',
    COUNT: 'inventory_counts:count',
    APPROVE: 'inventory_counts:approve',
    APPLY: 'inventory_counts:apply',
    CANCEL: 'inventory_counts:cancel',
  },
  SUPPLIER_INVOICES: {
    VIEW: 'supplier_invoices:view',
    CREATE: 'supplier_invoices:create',
    UPDATE: 'supplier_invoices:update',
    SUBMIT: 'supplier_invoices:submit',
    APPROVE: 'supplier_invoices:approve',
    DISPUTE: 'supplier_invoices:dispute',
    CANCEL: 'supplier_invoices:cancel',
    MATCH: 'supplier_invoices:match',
  },
  SUPPLIER_DELIVERY_NOTES: {
    VIEW: 'supplier_delivery_notes:view',
    CREATE: 'supplier_delivery_notes:create',
    RECEIVE: 'supplier_delivery_notes:receive',
    UPDATE: 'supplier_delivery_notes:update',
    DELETE: 'supplier_delivery_notes:delete',
  },
  THREE_WAY_MATCH: {
    VIEW: 'three_way_match:view',
    OVERRIDE: 'three_way_match:override',
  },
  SUPPLIER_CLAIMS: {
    VIEW: 'supplier_claims:view',
    CREATE: 'supplier_claims:create',
    SEND: 'supplier_claims:send',
    RESOLVE: 'supplier_claims:resolve',
    REJECT: 'supplier_claims:reject',
  },
  JURISDICTIONS: {
    VIEW: 'jurisdictions:view',
    CREATE: 'jurisdictions:create',
    UPDATE: 'jurisdictions:update',
    DELETE: 'jurisdictions:delete',
  },
  DELIVERY_NOTES: {
    VIEW: 'delivery_notes:view',
    CREATE: 'delivery_notes:create',
    ISSUE: 'delivery_notes:issue',
    CANCEL: 'delivery_notes:cancel',
    INVOICE: 'delivery_notes:invoice',
  },
  CREDIT_NOTES: {
    VIEW: 'credit_notes:view',
    CREATE: 'credit_notes:create',
    ISSUE: 'credit_notes:issue',
    APPLY: 'credit_notes:apply',
    CANCEL: 'credit_notes:cancel',
  },
  DEBIT_NOTES: {
    VIEW: 'debit_notes:view',
    CREATE: 'debit_notes:create',
    ISSUE: 'debit_notes:issue',
    CANCEL: 'debit_notes:cancel',
  },
  FISCAL: {
    VIEW_AUTHORIZATIONS: 'fiscal:view_authorizations',
  },
  CHECKS: {
    VIEW: 'checks:view',
    CREATE: 'checks:create',
    DEPOSIT: 'checks:deposit',
    CLEAR: 'checks:clear',
    BOUNCE: 'checks:bounce',
    ENDORSE: 'checks:endorse',
    RETURN: 'checks:return',
    CANCEL: 'checks:cancel',
  },
  COLLECTOR_RENDITIONS: {
    VIEW: 'collector_renditions:view',
    CREATE: 'collector_renditions:create',
    SUBMIT: 'collector_renditions:submit',
    APPROVE: 'collector_renditions:approve',
    REJECT: 'collector_renditions:reject',
  },
  BANK_ACCOUNTS: {
    VIEW: 'bank_accounts:view',
    CREATE: 'bank_accounts:create',
    UPDATE: 'bank_accounts:update',
    DELETE: 'bank_accounts:delete',
  },
  BANK_STATEMENTS: {
    VIEW: 'bank_statements:view',
    IMPORT: 'bank_statements:import',
    RECONCILE: 'bank_statements:reconcile',
    CLOSE: 'bank_statements:close',
  },
  RECONCILIATION: {
    VIEW: 'reconciliation:view',
    CONFIRM: 'reconciliation:confirm',
    REJECT: 'reconciliation:reject',
  },
  WITHHOLDINGS: {
    VIEW: 'withholdings:view',
    CREATE: 'withholdings:create',
    UPDATE: 'withholdings:update',
    DELETE: 'withholdings:delete',
  },
  WITHHOLDING_PADRONES: {
    VIEW: 'withholding_padrones:view',
    IMPORT: 'withholding_padrones:import',
    LOOKUP: 'withholding_padrones:lookup',
  },
  PAYMENT_ORDERS: {
    VIEW: 'payment_orders:view',
    CREATE: 'payment_orders:create',
    APPROVE: 'payment_orders:approve',
    PAY: 'payment_orders:pay',
    CANCEL: 'payment_orders:cancel',
  },
  PAYMENT_BATCHES: {
    VIEW: 'payment_batches:view',
    CREATE: 'payment_batches:create',
    GENERATE_FILE: 'payment_batches:generate_file',
    MARK_PROCESSED: 'payment_batches:mark_processed',
  },
  POS: {
    CREATE: 'pos:create',
    READ: 'pos:read',
    VOID: 'pos:void',
    OVERRIDE_PRICE: 'pos:override_price',
  },
  SEARCH: {
    VIEW: 'search:view',
  },
  SUPPORT_TICKETS: {
    VIEW: 'support_tickets:view',
    CREATE: 'support_tickets:create',
    UPDATE: 'support_tickets:update',
    COMMENT: 'support_tickets:comment',
    RESOLVE: 'support_tickets:resolve',
    DISPATCH_AGENT: 'support_tickets:dispatch_agent',
  },
};

// Flatten all permissions into an array
export function getAllPermissions(): string[] {
  const all: string[] = [];
  for (const group of Object.values(PERMISSIONS)) {
    for (const perm of Object.values(group)) {
      all.push(perm);
    }
  }
  return all;
}
