import { AppDataSource } from '../config/data-source';

/**
 * Hard-reset demo/transactional data, preserve bootstrap (roles, permissions,
 * admin user, company, CASA-CENTRAL branch, first warehouse, master-data).
 *
 * Strategy: TRUNCATE CASCADE bypasses TypeORM subscribers / service-level
 * eventBus emission, so audit listeners do not fire per row.
 */
export async function cleanupDemo() {
  if (process.env.NODE_ENV === 'production' && process.env.ALLOW_DEMO_IN_PROD !== 'true') {
    throw new Error('Refusing to run cleanup-demo in production. Set ALLOW_DEMO_IN_PROD=true to override.');
  }

  // Tables fully truncated and regenerated by the large-demo pipeline.
  const truncateTables = [
    'audit_events',
    'shipment_stops', 'shipments',
    'delivery_note_items', 'delivery_notes',
    'order_items', 'orders',
    'invoices',
    'credit_note_items', 'credit_notes',
    'debit_note_items', 'debit_notes',
    'payments',
    'checks',
    'commissions',
    'return_order_items', 'return_orders',
    'stock_reservations', 'stock_movements', 'stock',
    'inventory_count_lines', 'inventory_counts',
    'purchase_order_items', 'purchase_orders', 'purchase_receptions',
    'supplier_invoice_items', 'supplier_invoices',
    'supplier_delivery_notes', 'supplier_claims',
    'account_entries', 'accounts',
    'cashbox_sessions',
    'picking_task_items', 'picking_tasks',
    'dispatch_sheets',
    'price_list_items', 'price_lists',
    'stock_by_lot', 'lots',
    'payment_orders', 'payment_batches',
    'promotion_items', 'promotions',
    'three_way_matches', 'reconciliation_matches',
    'bank_statement_lines', 'bank_statements',
    'withholdings', 'withholding_padron',
    'addresses', 'contacts', 'customers',
    'product_variants', 'products',
    'brands',
    'suppliers',
    'drivers', 'vehicles',
    'bank_accounts',
  ];

  const qr = AppDataSource.createQueryRunner();
  await qr.connect();

  try {
    // Filter to existing tables to avoid TypeORM error logging on missing ones
    const existing = (await qr.query(
      `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`,
    )) as Array<{ table_name: string }>;
    const existingSet = new Set(existing.map((r) => r.table_name));
    for (const t of truncateTables) {
      if (!existingSet.has(t)) continue;
      await qr.query(`TRUNCATE TABLE "${t}" CASCADE`);
    }

    // Partial cleanups (preserve bootstrap rows)
    await qr.query(`DELETE FROM users WHERE email LIKE '%@demo.com'`);
    await qr.query(`DELETE FROM branches WHERE code != 'CASA-CENTRAL'`);
    await qr.query(`
      DELETE FROM warehouses
      WHERE id NOT IN (SELECT id FROM warehouses ORDER BY created_at ASC LIMIT 1)
    `);
    await qr.query(`
      DELETE FROM cashboxes
      WHERE name NOT IN ('Caja Principal', 'Caja Mostrador', 'Caja Chica')
    `);
  } finally {
    await qr.release();
  }
  console.log('  Demo cleanup completed');
}
