import { Entity, Column, ManyToOne, JoinColumn, Index, OneToMany } from 'typeorm';
import BaseEntity from '../../../common/base.entity';
import { SupportTicketEntity } from './support-ticket.entity';
import { SupportTicketAttachmentEntity } from './support-ticket-attachment.entity';

/**
 * Canonical chat source for a support ticket. Drives the UI timeline that
 * the customer sees: their own messages, replies from "Soporte" (whether AI
 * or human), and human-readable system messages for state changes.
 *
 * `support_ticket_events` remains a private audit log for tool invocations,
 * SSE frames, and other internal signals that should not leak to the
 * customer-facing chat.
 */
@Entity('support_ticket_messages')
export class SupportTicketMessageEntity extends BaseEntity {
  @Index()
  @Column({ name: 'ticket_id', type: 'varchar', length: 40 })
  ticketId: string;

  @ManyToOne(() => SupportTicketEntity, { onDelete: 'CASCADE' })
  @JoinColumn({ name: 'ticket_id' })
  ticket: SupportTicketEntity;

  // customer = person who opened the ticket
  // support  = anyone acting as support (AI agent or human operator)
  // system   = ERP-generated notice (state changes, handoffs, etc.)
  @Column({ name: 'sender_role' })
  senderRole: 'customer' | 'support' | 'system';

  // user   = a human typed this
  // ai     = Hermes generated this
  // system = auto-generated by the ERP
  @Column({ name: 'sender_kind' })
  senderKind: 'user' | 'ai' | 'system';

  @Column({ name: 'sender_user_id', type: 'varchar', length: 40, nullable: true })
  senderUserId: string | null;

  @Column({ type: 'text', nullable: true })
  body: string | null;

  @Column({ default: 'sent' })
  status: 'sent' | 'failed';

  @OneToMany(() => SupportTicketAttachmentEntity, (a) => a.message)
  attachments: SupportTicketAttachmentEntity[];
}
